name: CI

on:
  push:
    branches: [ ci-cd ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t "$REGISTRY_IMAGE:${GITHUB_SHA:0:4}" .
      env:
        REGISTRY_IMAGE: amasselot/mad-client

    - name: Login to Docker Registry
      run: echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USERNAME --password-stdin $REGISTRY_ENDPOINT
      env:
        # Update REGISTRY_ENDPOINT if you are targetting a specific registry
        # Here I'm using default Docker Hub
        REGISTRY_ENDPOINT: ""
        REGISTRY_USERNAME: amasselot
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Push docker image
      run: docker push "$REGISTRY_IMAGE:${GITHUB_SHA:0:4}"
      env:
        REGISTRY_IMAGE: amasselot/mad-client
